### ISSUE TITLE
new plugin: "deep-assoc-completion" 

### ISSUE THREAD

**Issue by voku** [WyriHaximus/awesome-phpstorm#20]
https://plugins.jetbrains.com/plugin/9927-deep-assoc-completion

PS: it's also working with mysqli and PDO results :fire:

**Comment by WyriHaximus** [comment]
That's pretty cool! Would you mind creating a PR to add it?

**Comment by voku** [comment]
https://github.com/WyriHaximus/awesome-phpstorm/pull/22
