### ISSUE TITLE
Add Better Highlights plugin

### ISSUE THREAD

**Issue by clutcher** [WyriHaximus/awesome-phpstorm#33]
Plugin to improve highlighting of comments and keywords. Also allows to reference source code in comments - https://plugins.jetbrains.com/plugin/12895-better-highlights

**Comment by WyriHaximus** [comment]
Hey @clutcher, feel free to open a PR adding it to the list :+1:

**Comment by clutcher** [comment]
@WyriHaximus Created PR #34

**Comment by WyriHaximus** [comment]
@clutcher Thanks! Merged it in :+1:
